name: address_sf_package
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_html: ^3.0.0-beta.1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/locale/
    - assets/address/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: San Francisco Display
      fonts:
        - asset: assets/fonts/SanFranciscoDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SanFranciscoDisplayBold.ttf
          weight: 700
    - family: SVN-Mont
      fonts:
        - asset: assets/fonts/SVNMontBold.ttf
          weight: 700
